% matlab/convert_rirs_to_mat.m
% ─────────────────────────────────────────────────────────────────────────
% Convert pyroomacoustics .npy RIR files → .mat format for MATLAB.
% Requires Python + numpy on the system PATH.
%
% Usage (run from matlab/ directory):
%   >> convert_rirs_to_mat('../data/rirs', '../data/rirs_mat')

function convert_rirs_to_mat(input_dir, output_dir)

if nargin < 1, input_dir  = '../data/rirs';     end
if nargin < 2, output_dir = '../data/rirs_mat'; end

if ~exist(output_dir, 'dir'), mkdir(output_dir); end

% ── Use Python to batch-convert .npy → .mat ──────────────────────────
py_script = [tempname '.py'];
fid = fopen(py_script, 'w');
fprintf(fid, ['import numpy as np\n' ...
              'import scipy.io\n' ...
              'import json\n' ...
              'from pathlib import Path\n\n' ...
              'src = Path("%s")\n' ...
              'dst = Path("%s")\n' ...
              'dst.mkdir(parents=True, exist_ok=True)\n\n' ...
              'meta_json = src / "rir_metadata.json"\n' ...
              'meta_mat  = []\n' ...
              'if meta_json.exists():\n' ...
              '    with open(meta_json) as f:\n' ...
              '        records = json.load(f)\n' ...
              'else:\n' ...
              '    records = [{"file": p.name.replace(\".npy\",\"\"), "rt60": 0.5}\n' ...
              '                for p in sorted(src.glob("room_*.npy"))]\n\n' ...
              'for rec in records:\n' ...
              '    npy_file = src / (rec["file"].replace(".npy","") + ".npy")\n' ...
              '    if not npy_file.exists(): continue\n' ...
              '    rir = np.load(npy_file).astype(np.float32)\n' ...
              '    mat_name = npy_file.stem + ".mat"\n' ...
              '    scipy.io.savemat(str(dst / mat_name), {"rir": rir, "rt60": rec["rt60"]})\n' ...
              '    meta_mat.append({"file": mat_name, "rt60": float(rec["rt60"]),\n' ...
              '                     "room_dims": rec.get("room_dims",[]),\n' ...
              '                     "doa_deg":   rec.get("doa_deg", 90)})\n\n' ...
              'print(f"Converted {len(meta_mat)} files")\n'], ...
    input_dir, output_dir);
fclose(fid);

[status, out] = system(['python ' py_script]);
delete(py_script);

if status ~= 0
    error('Python conversion failed. Check Python/numpy/scipy are on PATH.\n%s', out);
end
fprintf('%s\n', out);

% ── Load JSON metadata and save as .mat struct ────────────────────────
meta_json_path = fullfile(input_dir, 'rir_metadata.json');
if exist(meta_json_path, 'file')
    fid = fopen(meta_json_path);
    raw = fread(fid, inf, 'uint8=>char')';
    fclose(fid);
    records = jsondecode(raw);

    % Convert to struct array
    metadata = struct('file', {}, 'rt60', {}, 'doa_deg', {});
    for k = 1:numel(records)
        r = records(k);
        mat_name = strrep(r.file, '.npy', '.mat');
        metadata(k).file    = mat_name;
        metadata(k).rt60    = r.rt60;
        metadata(k).doa_deg = r.doa_deg;
    end

    save(fullfile(output_dir, 'rir_metadata.mat'), 'metadata');
    fprintf('Saved rir_metadata.mat (%d entries)\n', numel(metadata));
end

fprintf('✓ RIR conversion complete → %s\n', output_dir);
end
